# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brief',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
